# Generated by Django 3.1.14 on 2024-04-30 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Metter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('airms', models.DecimalField(decimal_places=2, max_digits=10)),
                ('birms', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cirms', models.DecimalField(decimal_places=2, max_digits=10)),
                ('avrms', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bvrms', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cvrms', models.DecimalField(decimal_places=2, max_digits=10)),
                ('awatt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bwatt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cwatt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('avar', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bvar', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cvar', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ava', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bva', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cva', models.DecimalField(decimal_places=2, max_digits=10)),
                ('awatthr_hi', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bwatthr_hi', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cwatthr_hi', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.BigIntegerField()),
                ('index', models.IntegerField()),
            ],
            options={
                'db_table': 'metter',
            },
        ),
    ]
