{
 "title": "Smartmeter Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Live Daten", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Zählerstand Gas",
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "m3" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "1",
     "measurement": "energy",
     "query": "from(bucket: \"smartmeter\")\n  |> range(start: -1d)\n  |> filter(fn: (r) =>\n    r.topic == \"energy/gas/Verbrauch\"\n  )\n  |> last()",
     "select": [
      [
       { "params": [ "WirkenergieL1" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / 1000" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Gasverbrauch dieses Jahr",
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "m3" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "import \"strings\"\n\nmonth = time(v: \"${strings.substring(v: string(v: now()), start: 0, end: 5)}01-01T00:00:00Z\") from(bucket: \"gas-downsampled-spread\") |> range(start: month) |> filter(fn: (r) => r.topic == \"energy/gas/Verbrauch\") |> sum()",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Gaskosten dieses Jahr",
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "import \"strings\"\n\nmonth = time(v: \"${strings.substring(v: string(v: now()), start: 0, end: 5)}01-01T00:00:00Z\") from(bucket: \"gas-downsampled-spread\") |> range(start: month) |> filter(fn: (r) => r.topic == \"energy/gas/Verbrauch\") |> sum()\n|> map(fn: (r) => ({\n      r with\n      _value: r._value * 0.86868\n    })\n  )",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Zählerstand Strom",
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "1",
     "measurement": "energy",
     "query": "from(bucket: \"smartmeter\")\n  |> range(start: -1d)\n  |> filter(fn: (r) =>\n    r.topic == \"energy/Wirkenergie_L1-L3\"\n  )\n  |> last()",
     "select": [
      [
       { "params": [ "WirkenergieL1" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / 1000" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Stromverbrauch dieses Jahr",
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 8, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "import \"strings\"\n\nmonth = time(v: \"${strings.substring(v: string(v: now()), start: 0, end: 5)}01-01T00:00:00Z\") from(bucket: \"smartmeter-downsampled-spread\") |> range(start: month) |> filter(fn: (r) => r.topic == \"energy/Wirkenergie_L1-L3\") |> sum()",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Stromkosten dieses Jahr",
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "import \"strings\"\n\nmonth = time(v: \"${strings.substring(v: string(v: now()), start: 0, end: 5)}01-01T00:00:00Z\") from(bucket: \"smartmeter-downsampled-spread\") |> range(start: month) |> filter(fn: (r) => r.topic == \"energy/Wirkenergie_L1-L3\") |> sum()\n|> map(fn: (r) => ({\n      r with\n      _value: r._value * 0.2523\n    })\n  )",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Wirkleistung L1",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "energy",
     "query": "from(bucket: \"smartmeter\")\n  |> range(start: -5m)\n  |> filter(fn: (r) =>\n    r.topic == \"energy/Wirkleistung_L1\"\n  )\n  |> last()",
     "select": [
      [
       { "params": [ "WirkleistungL1" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Wirkleistung L2",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "energy",
     "query": "from(bucket: \"smartmeter\")\n  |> range(start: -5m)\n  |> filter(fn: (r) =>\n    r.topic == \"energy/Wirkleistung_L2\"\n  )\n  |> last()",
     "select": [
      [
       { "params": [ "WirkleistungL2" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Wirkleistung L3",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "energy",
     "query": "from(bucket: \"smartmeter\")\n  |> range(start: -5m)\n  |> filter(fn: (r) =>\n    r.topic == \"energy/Wirkleistung_L3\"\n  )\n  |> last()",
     "select": [
      [
       { "params": [ "WirkleistungL3" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Strom L1",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "energy",
     "query": "from(bucket: \"smartmeter\")\n  |> range(start: -5m)\n  |> filter(fn: (r) =>\n    r.topic == \"energy/Strom_L1\"\n  )\n  |> last()",
     "select": [
      [
       { "params": [ "WirkleistungL1" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Strom L2",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "energy",
     "query": "from(bucket: \"smartmeter\")\n  |> range(start: -5m)\n  |> filter(fn: (r) =>\n    r.topic == \"energy/Strom_L2\"\n  )\n  |> last()",
     "select": [
      [
       { "params": [ "WirkleistungL1" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Strom L3",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "energy",
     "query": "from(bucket: \"smartmeter\")\n  |> range(start: -5m)\n  |> filter(fn: (r) =>\n    r.topic == \"energy/Strom_L3\"\n  )\n  |> last()",
     "select": [
      [
       { "params": [ "WirkleistungL1" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Leistung",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "alias": "Wirkleistung L1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "energy",
     "query": "from(bucket: \"smartmeter\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r.topic == \"energy/Wirkleistung_L1\"\n  )",
     "select": [
      [
       { "params": [ "WirkleistungL1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Wirkleistung L2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "energy",
     "query": "from(bucket: \"smartmeter\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r.topic == \"energy/Wirkleistung_L2\"\n  )",
     "select": [
      [
       { "params": [ "WirkleistungL2" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Wirkleistung L3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "energy",
     "query": "from(bucket: \"smartmeter\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r.topic == \"energy/Wirkleistung_L3\"\n  )",
     "select": [
      [
       { "params": [ "WirkleistungL3" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Historische Daten",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Tagesverbrauch / h",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "kwatth" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "import \"strings\"\r\n\r\nday = time(v: \"${strings.substring(v: string(v: now()), start: 0, end: 10)}T00:00:00+01:00\") from(bucket: \"smartmeter-downsampled-spread\")|> range(start: day) |> filter(fn: (r) => r.topic == \"energy/Wirkenergie_L1-L3\") |> aggregateWindow(\r\n    every: 1h,\r\n    fn: sum,\r\n    timeSrc: \"_start\",\r\n    createEmpty: false\r\n)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Monatsverbrauch / Tag",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "kwatth" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "import \"strings\"\r\n\r\nmonth = time(v: \"${strings.substring(v: string(v: now()), start: 0, end: 8)}01T00:00:00Z\") from(bucket: \"smartmeter-downsampled-spread\") |> range(start: month) |> filter(fn: (r) => r.topic == \"energy/Wirkenergie_L1-L3\") |> aggregateWindow(\r\n    every: 24h,\r\n    fn: sum,\r\n    timeSrc: \"_start\",\r\n    createEmpty: false\r\n)\r\n",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Jahresverbrauch / Tag",
     "type": "marcusolsson-hourly-heatmap-panel",
     "gridPos": { "h": 16, "w": 24, "x": 0, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "kwatth" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "import \"strings\"\r\n\r\nmonth = time(v: \"${strings.substring(v: string(v: now()), start: 0, end: 5)}01-01T00:00:00Z\") from(bucket: \"smartmeter-downsampled-spread\") |> range(start: month) |> filter(fn: (r) => r.topic == \"energy/Wirkenergie_L1-L3\") |> aggregateWindow(\r\n    every: 1h,\r\n    fn: sum,\r\n    timeSrc: \"_start\",\r\n    createEmpty: true\r\n)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  }
 ]
}