import sys
from PyQt5 import QtCore, QtGui, QtWidgets
import matplotlib.pyplot as plt
from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FigureCanvas
from matplotlib.animation import FuncAnimation
from collections import deque
from itertools import count
import random



class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(587, 480)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../env/source/icons/favicon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("background-color: rgb(0, 65, 106);\n"
"padding-right: 0;")
        MainWindow.setIconSize(QtCore.QSize(20, 20))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("margin: 0 0;")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_6 = QtWidgets.QFrame(self.frame)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.label_23 = QtWidgets.QLabel(self.frame_6)
        self.label_23.setGeometry(QtCore.QRect(0, 30, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_23.setFont(font)
        self.label_23.setStyleSheet("color: white;")
        self.label_23.setObjectName("label_23")
        self.horizontalLayout.addWidget(self.frame_6)
        self.frame_7 = QtWidgets.QFrame(self.frame)
        self.frame_7.setStyleSheet("")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.frame_3 = QtWidgets.QFrame(self.frame_7)
        self.frame_3.setGeometry(QtCore.QRect(0, 0, 141, 31))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label_32 = QtWidgets.QLabel(self.frame_3)
        self.label_32.setGeometry(QtCore.QRect(0, 0, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_32.setFont(font)
        self.label_32.setStyleSheet("color: rgb(0, 85, 255);")
        self.label_32.setAlignment(QtCore.Qt.AlignCenter)
        self.label_32.setObjectName("label_32")
        self.frame_21 = QtWidgets.QFrame(self.frame_7)
        self.frame_21.setGeometry(QtCore.QRect(-1, 49, 141, 41))
        self.frame_21.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_21.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_21.setObjectName("frame_21")
        self.label_27 = QtWidgets.QLabel(self.frame_21)
        self.label_27.setGeometry(QtCore.QRect(50, -20, 41, 20))
        self.label_27.setAlignment(QtCore.Qt.AlignCenter)
        self.label_27.setObjectName("label_27")
        self.label_31 = QtWidgets.QLabel(self.frame_21)
        self.label_31.setGeometry(QtCore.QRect(90, 10, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_31.setFont(font)
        self.label_31.setStyleSheet("color: rgb(255, 255, 0);")
        self.label_31.setAlignment(QtCore.Qt.AlignCenter)
        self.label_31.setObjectName("label_31")
        self.label_33 = QtWidgets.QLabel(self.frame_21)
        self.label_33.setGeometry(QtCore.QRect(50, 10, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_33.setFont(font)
        self.label_33.setStyleSheet("color: rgb(255, 170, 0);")
        self.label_33.setAlignment(QtCore.Qt.AlignCenter)
        self.label_33.setObjectName("label_33")
        self.label_34 = QtWidgets.QLabel(self.frame_21)
        self.label_34.setGeometry(QtCore.QRect(0, 10, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_34.setFont(font)
        self.label_34.setStyleSheet("color: rgb(255, 0, 0);")
        self.label_34.setAlignment(QtCore.Qt.AlignCenter)
        self.label_34.setObjectName("label_34")
        self.frame_4 = QtWidgets.QFrame(self.frame_7)
        self.frame_4.setGeometry(QtCore.QRect(-1, 30, 141, 21))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.frame_10 = QtWidgets.QFrame(self.frame_4)
        self.frame_10.setGeometry(QtCore.QRect(0, 0, 41, 20))
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.label_15 = QtWidgets.QLabel(self.frame_10)
        self.label_15.setGeometry(QtCore.QRect(0, 0, 51, 21))
        self.label_15.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.frame_11 = QtWidgets.QFrame(self.frame_4)
        self.frame_11.setGeometry(QtCore.QRect(50, 0, 41, 20))
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.label_18 = QtWidgets.QLabel(self.frame_11)
        self.label_18.setGeometry(QtCore.QRect(0, 0, 51, 20))
        self.label_18.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.frame_12 = QtWidgets.QFrame(self.frame_4)
        self.frame_12.setGeometry(QtCore.QRect(100, 0, 41, 20))
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.label_28 = QtWidgets.QLabel(self.frame_12)
        self.label_28.setGeometry(QtCore.QRect(-10, 0, 51, 21))
        self.label_28.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_28.setAlignment(QtCore.Qt.AlignCenter)
        self.label_28.setObjectName("label_28")
        self.horizontalLayout.addWidget(self.frame_7)
        self.frame_8 = QtWidgets.QFrame(self.frame)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.frame_48 = QtWidgets.QFrame(self.frame_8)
        self.frame_48.setGeometry(QtCore.QRect(0, 0, 138, 96))
        self.frame_48.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_48.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_48.setObjectName("frame_48")
        self.frame_104 = QtWidgets.QFrame(self.frame_48)
        self.frame_104.setGeometry(QtCore.QRect(0, 0, 141, 31))
        self.frame_104.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_104.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_104.setObjectName("frame_104")
        self.label_124 = QtWidgets.QLabel(self.frame_104)
        self.label_124.setGeometry(QtCore.QRect(0, 0, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_124.setFont(font)
        self.label_124.setStyleSheet("color: rgb(255, 255, 0);")
        self.label_124.setAlignment(QtCore.Qt.AlignCenter)
        self.label_124.setObjectName("label_124")
        self.frame_105 = QtWidgets.QFrame(self.frame_48)
        self.frame_105.setGeometry(QtCore.QRect(-1, 49, 141, 41))
        self.frame_105.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_105.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_105.setObjectName("frame_105")
        self.label_125 = QtWidgets.QLabel(self.frame_105)
        self.label_125.setGeometry(QtCore.QRect(50, -20, 41, 20))
        self.label_125.setAlignment(QtCore.Qt.AlignCenter)
        self.label_125.setObjectName("label_125")
        self.label_126 = QtWidgets.QLabel(self.frame_105)
        self.label_126.setGeometry(QtCore.QRect(90, 10, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_126.setFont(font)
        self.label_126.setStyleSheet("color: rgb(255, 255, 0);")
        self.label_126.setAlignment(QtCore.Qt.AlignCenter)
        self.label_126.setObjectName("label_126")
        self.label_127 = QtWidgets.QLabel(self.frame_105)
        self.label_127.setGeometry(QtCore.QRect(50, 10, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_127.setFont(font)
        self.label_127.setStyleSheet("color: rgb(255, 170, 0);")
        self.label_127.setAlignment(QtCore.Qt.AlignCenter)
        self.label_127.setObjectName("label_127")
        self.label_128 = QtWidgets.QLabel(self.frame_105)
        self.label_128.setGeometry(QtCore.QRect(0, 10, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_128.setFont(font)
        self.label_128.setStyleSheet("color: rgb(255, 0, 0);")
        self.label_128.setAlignment(QtCore.Qt.AlignCenter)
        self.label_128.setObjectName("label_128")
        self.frame_106 = QtWidgets.QFrame(self.frame_48)
        self.frame_106.setGeometry(QtCore.QRect(-1, 30, 141, 21))
        self.frame_106.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_106.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_106.setObjectName("frame_106")
        self.frame_107 = QtWidgets.QFrame(self.frame_106)
        self.frame_107.setGeometry(QtCore.QRect(0, 0, 41, 20))
        self.frame_107.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_107.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_107.setObjectName("frame_107")
        self.label_129 = QtWidgets.QLabel(self.frame_107)
        self.label_129.setGeometry(QtCore.QRect(0, 0, 51, 21))
        self.label_129.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_129.setAlignment(QtCore.Qt.AlignCenter)
        self.label_129.setObjectName("label_129")
        self.frame_108 = QtWidgets.QFrame(self.frame_106)
        self.frame_108.setGeometry(QtCore.QRect(50, 0, 41, 20))
        self.frame_108.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_108.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_108.setObjectName("frame_108")
        self.label_130 = QtWidgets.QLabel(self.frame_108)
        self.label_130.setGeometry(QtCore.QRect(0, 0, 51, 20))
        self.label_130.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_130.setAlignment(QtCore.Qt.AlignCenter)
        self.label_130.setObjectName("label_130")
        self.frame_109 = QtWidgets.QFrame(self.frame_106)
        self.frame_109.setGeometry(QtCore.QRect(100, 0, 41, 20))
        self.frame_109.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_109.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_109.setObjectName("frame_109")
        self.label_131 = QtWidgets.QLabel(self.frame_109)
        self.label_131.setGeometry(QtCore.QRect(-10, 0, 41, 21))
        self.label_131.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_131.setAlignment(QtCore.Qt.AlignCenter)
        self.label_131.setObjectName("label_131")
        self.horizontalLayout.addWidget(self.frame_8)
        self.frame_9 = QtWidgets.QFrame(self.frame)
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.frame_117 = QtWidgets.QFrame(self.frame_9)
        self.frame_117.setGeometry(QtCore.QRect(0, 0, 138, 96))
        self.frame_117.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_117.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_117.setObjectName("frame_117")
        self.frame_136 = QtWidgets.QFrame(self.frame_117)
        self.frame_136.setGeometry(QtCore.QRect(0, 0, 141, 31))
        self.frame_136.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_136.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_136.setObjectName("frame_136")
        self.label_164 = QtWidgets.QLabel(self.frame_136)
        self.label_164.setGeometry(QtCore.QRect(0, 10, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_164.setFont(font)
        self.label_164.setStyleSheet("color: rgb(85, 170, 0);")
        self.label_164.setAlignment(QtCore.Qt.AlignCenter)
        self.label_164.setObjectName("label_164")
        self.frame_137 = QtWidgets.QFrame(self.frame_117)
        self.frame_137.setGeometry(QtCore.QRect(-1, 49, 141, 41))
        self.frame_137.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_137.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_137.setObjectName("frame_137")
        self.label_165 = QtWidgets.QLabel(self.frame_137)
        self.label_165.setGeometry(QtCore.QRect(50, -20, 41, 20))
        self.label_165.setAlignment(QtCore.Qt.AlignCenter)
        self.label_165.setObjectName("label_165")
        self.label_166 = QtWidgets.QLabel(self.frame_137)
        self.label_166.setGeometry(QtCore.QRect(90, 10, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_166.setFont(font)
        self.label_166.setStyleSheet("color: rgb(255, 255, 0);")
        self.label_166.setAlignment(QtCore.Qt.AlignCenter)
        self.label_166.setObjectName("label_166")
        self.label_167 = QtWidgets.QLabel(self.frame_137)
        self.label_167.setGeometry(QtCore.QRect(50, 10, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_167.setFont(font)
        self.label_167.setStyleSheet("color: rgb(255, 170, 0);")
        self.label_167.setAlignment(QtCore.Qt.AlignCenter)
        self.label_167.setObjectName("label_167")
        self.label_168 = QtWidgets.QLabel(self.frame_137)
        self.label_168.setGeometry(QtCore.QRect(0, 10, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_168.setFont(font)
        self.label_168.setStyleSheet("color: rgb(255, 0, 0);")
        self.label_168.setAlignment(QtCore.Qt.AlignCenter)
        self.label_168.setObjectName("label_168")
        self.frame_138 = QtWidgets.QFrame(self.frame_117)
        self.frame_138.setGeometry(QtCore.QRect(-1, 30, 141, 21))
        self.frame_138.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_138.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_138.setObjectName("frame_138")
        self.frame_139 = QtWidgets.QFrame(self.frame_138)
        self.frame_139.setGeometry(QtCore.QRect(0, 0, 41, 20))
        self.frame_139.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_139.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_139.setObjectName("frame_139")
        self.label_169 = QtWidgets.QLabel(self.frame_139)
        self.label_169.setGeometry(QtCore.QRect(0, 0, 51, 21))
        self.label_169.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_169.setAlignment(QtCore.Qt.AlignCenter)
        self.label_169.setObjectName("label_169")
        self.frame_140 = QtWidgets.QFrame(self.frame_138)
        self.frame_140.setGeometry(QtCore.QRect(50, 0, 41, 20))
        self.frame_140.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_140.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_140.setObjectName("frame_140")
        self.label_170 = QtWidgets.QLabel(self.frame_140)
        self.label_170.setGeometry(QtCore.QRect(0, 0, 51, 20))
        self.label_170.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_170.setAlignment(QtCore.Qt.AlignCenter)
        self.label_170.setObjectName("label_170")
        self.frame_141 = QtWidgets.QFrame(self.frame_138)
        self.frame_141.setGeometry(QtCore.QRect(100, 0, 41, 20))
        self.frame_141.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_141.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_141.setObjectName("frame_141")
        self.label_171 = QtWidgets.QLabel(self.frame_141)
        self.label_171.setGeometry(QtCore.QRect(-10, 0, 41, 21))
        self.label_171.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_171.setAlignment(QtCore.Qt.AlignCenter)
        self.label_171.setObjectName("label_171")
        self.horizontalLayout.addWidget(self.frame_9)
        self.verticalLayout.addWidget(self.frame)
        self.frame_35 = QtWidgets.QFrame(self.centralwidget)
        self.frame_35.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_35.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_35.setObjectName("frame_35")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_35)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.frame_36 = QtWidgets.QFrame(self.frame_35)
        self.frame_36.setStyleSheet("")
        self.frame_36.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_36.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_36.setObjectName("frame_36")
        self.label_24 = QtWidgets.QLabel(self.frame_36)
        self.label_24.setGeometry(QtCore.QRect(0, 30, 101, 16))
        self.label_24.setStyleSheet("color: rgb(0, 255, 0);")
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(self.frame_36)
        self.label_25.setGeometry(QtCore.QRect(0, 50, 101, 21))
        self.label_25.setStyleSheet("color: rgb(0, 255, 127);")
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.frame_36)
        self.label_26.setGeometry(QtCore.QRect(0, 70, 101, 20))
        self.label_26.setStyleSheet("color: rgb(0, 255, 0);")
        self.label_26.setObjectName("label_26")
        self.label_35 = QtWidgets.QLabel(self.frame_36)
        self.label_35.setGeometry(QtCore.QRect(0, 0, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_35.setFont(font)
        self.label_35.setStyleSheet("color: rgb(0, 255, 0);")
        self.label_35.setObjectName("label_35")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame_36)
        self.stackedWidget.setGeometry(QtCore.QRect(100, 20, 120, 80))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.stackedWidget.addWidget(self.page_2)
        self.horizontalLayout_5.addWidget(self.frame_36)
        self.frame_37 = QtWidgets.QFrame(self.frame_35)
        self.frame_37.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_37.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_37.setObjectName("frame_37")
        self.label_19 = QtWidgets.QLabel(self.frame_37)
        self.label_19.setGeometry(QtCore.QRect(0, 0, 111, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setStyleSheet("color: rgb(0, 85, 255);")
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.frame_114 = QtWidgets.QFrame(self.frame_37)
        self.frame_114.setGeometry(QtCore.QRect(60, 70, 111, 71))
        self.frame_114.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_114.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_114.setObjectName("frame_114")
        self.visu = QtWidgets.QWidget(self.frame_37)
        self.visu.setGeometry(QtCore.QRect(0, 20, 101, 71))
        self.visu.setObjectName("visu")
        self.horizontalLayout_5.addWidget(self.frame_37)
        self.frame_38 = QtWidgets.QFrame(self.frame_35)
        self.frame_38.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_38.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_38.setObjectName("frame_38")
        self.label_20 = QtWidgets.QLabel(self.frame_38)
        self.label_20.setGeometry(QtCore.QRect(0, 0, 111, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setStyleSheet("color: rgb(255, 255, 0);")
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.frame_115 = QtWidgets.QFrame(self.frame_38)
        self.frame_115.setGeometry(QtCore.QRect(0, 20, 111, 71))
        self.frame_115.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_115.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_115.setObjectName("frame_115")
        self.horizontalLayout_5.addWidget(self.frame_38)
        self.frame_39 = QtWidgets.QFrame(self.frame_35)
        self.frame_39.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_39.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_39.setObjectName("frame_39")
        self.label_21 = QtWidgets.QLabel(self.frame_39)
        self.label_21.setGeometry(QtCore.QRect(10, 0, 101, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setStyleSheet("color: rgb(0, 255, 127);")
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName("label_21")
        self.frame_112 = QtWidgets.QFrame(self.frame_39)
        self.frame_112.setGeometry(QtCore.QRect(0, 20, 111, 71))
        self.frame_112.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_112.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_112.setObjectName("frame_112")
        self.horizontalLayout_5.addWidget(self.frame_39)
        self.frame_40 = QtWidgets.QFrame(self.frame_35)
        self.frame_40.setStyleSheet("background-color: rgb(0, 94, 153);")
        self.frame_40.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_40.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_40.setObjectName("frame_40")
        self.label_22 = QtWidgets.QLabel(self.frame_40)
        self.label_22.setGeometry(QtCore.QRect(0, 0, 111, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setStyleSheet("color: rgb(255, 170, 0);")
        self.label_22.setAlignment(QtCore.Qt.AlignCenter)
        self.label_22.setObjectName("label_22")
        self.frame_113 = QtWidgets.QFrame(self.frame_40)
        self.frame_113.setGeometry(QtCore.QRect(0, 20, 111, 71))
        self.frame_113.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_113.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_113.setObjectName("frame_113")
        self.label_30 = QtWidgets.QLabel(self.frame_113)
        self.label_30.setGeometry(QtCore.QRect(0, 9, 111, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_30.setFont(font)
        self.label_30.setStyleSheet("color: rgb(255, 255, 0);")
        self.label_30.setAlignment(QtCore.Qt.AlignCenter)
        self.label_30.setObjectName("label_30")
        self.horizontalLayout_5.addWidget(self.frame_40)
        self.verticalLayout.addWidget(self.frame_35)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_16 = QtWidgets.QFrame(self.frame_2)
        self.frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.pushButton = QtWidgets.QPushButton(self.frame_16)
        self.pushButton.setGeometry(QtCore.QRect(0, 0, 111, 61))
        self.pushButton.setMouseTracking(False)
        self.pushButton.setStyleSheet("border-radius: 5px;\n"
"border: 1px solid orange;\n"
"margin-right: 2px;")
        self.pushButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("source/icons/Setting.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon1)
        self.pushButton.setIconSize(QtCore.QSize(60, 60))
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(self.frame_16)
        self.label.setGeometry(QtCore.QRect(0, 70, 111, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.frame_16)
        self.frame_17 = QtWidgets.QFrame(self.frame_2)
        self.frame_17.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setObjectName("frame_17")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_17)
        self.pushButton_2.setGeometry(QtCore.QRect(0, 0, 111, 61))
        self.pushButton_2.setStyleSheet("border-radius: 5px;\n"
"border: 1px solid rgb(0, 85, 255);;\n"
"margin-right: 2px;")
        self.pushButton_2.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("source/icons/voltage-metter.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon2)
        self.pushButton_2.setIconSize(QtCore.QSize(60, 60))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_2 = QtWidgets.QLabel(self.frame_17)
        self.label_2.setGeometry(QtCore.QRect(0, 70, 111, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.frame_17)
        self.frame_18 = QtWidgets.QFrame(self.frame_2)
        self.frame_18.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_18.setObjectName("frame_18")
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_18)
        self.pushButton_3.setGeometry(QtCore.QRect(0, 0, 111, 61))
        self.pushButton_3.setStyleSheet("border-radius: 5px;\n"
"border: 1px solid rgb(255, 255, 0);\n"
"margin-right: 2px;")
        self.pushButton_3.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("source/icons/current-metter.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon3)
        self.pushButton_3.setIconSize(QtCore.QSize(60, 60))
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_3 = QtWidgets.QLabel(self.frame_18)
        self.label_3.setGeometry(QtCore.QRect(0, 70, 111, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.frame_18)
        self.frame_19 = QtWidgets.QFrame(self.frame_2)
        self.frame_19.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_19.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_19.setObjectName("frame_19")
        self.pushButton_4 = QtWidgets.QPushButton(self.frame_19)
        self.pushButton_4.setGeometry(QtCore.QRect(0, 0, 111, 61))
        self.pushButton_4.setStyleSheet("border-radius: 5px;\n"
"border: 1px solid rgb(170, 0, 255);\n"
"margin-right: 2px;")
        self.pushButton_4.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("source/icons/angle.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_4.setIcon(icon4)
        self.pushButton_4.setIconSize(QtCore.QSize(60, 60))
        self.pushButton_4.setObjectName("pushButton_4")
        self.label_8 = QtWidgets.QLabel(self.frame_19)
        self.label_8.setGeometry(QtCore.QRect(0, 70, 111, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_2.addWidget(self.frame_19)
        self.frame_20 = QtWidgets.QFrame(self.frame_2)
        self.frame_20.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_20.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_20.setObjectName("frame_20")
        self.pushButton_5 = QtWidgets.QPushButton(self.frame_20)
        self.pushButton_5.setGeometry(QtCore.QRect(0, 0, 111, 61))
        self.pushButton_5.setStyleSheet("border-radius: 5px;\n"
"border: 1px solid rgb(0, 255, 0);\n"
"margin-right: 2px;")
        self.pushButton_5.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("source/icons/power.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_5.setIcon(icon5)
        self.pushButton_5.setIconSize(QtCore.QSize(60, 60))
        self.pushButton_5.setObjectName("pushButton_5")
        self.label_9 = QtWidgets.QLabel(self.frame_20)
        self.label_9.setGeometry(QtCore.QRect(0, 70, 111, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_2.addWidget(self.frame_20)
        self.verticalLayout.addWidget(self.frame_2)
        self.frame_5 = QtWidgets.QFrame(self.centralwidget)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.frame_31 = QtWidgets.QFrame(self.frame_5)
        self.frame_31.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_31.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_31.setObjectName("frame_31")
        self.pushButton_6 = QtWidgets.QPushButton(self.frame_31)
        self.pushButton_6.setGeometry(QtCore.QRect(0, 0, 111, 61))
        self.pushButton_6.setStyleSheet("border-radius: 10px;\n"
"border: 1px solid red;\n"
"margin-right: 2px;")
        self.pushButton_6.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("source/icons/Hamonic.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_6.setIcon(icon6)
        self.pushButton_6.setIconSize(QtCore.QSize(60, 60))
        self.pushButton_6.setObjectName("pushButton_6")
        self.label_10 = QtWidgets.QLabel(self.frame_31)
        self.label_10.setGeometry(QtCore.QRect(0, 70, 111, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_6.addWidget(self.frame_31)
        self.frame_32 = QtWidgets.QFrame(self.frame_5)
        self.frame_32.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_32.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_32.setObjectName("frame_32")
        self.pushButton_7 = QtWidgets.QPushButton(self.frame_32)
        self.pushButton_7.setGeometry(QtCore.QRect(10, 0, 91, 61))
        self.pushButton_7.setStyleSheet("border-radius: 5px;\n"
"border: 1px solid white;")
        self.pushButton_7.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("source/icons/view-2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_7.setIcon(icon7)
        self.pushButton_7.setIconSize(QtCore.QSize(60, 60))
        self.pushButton_7.setObjectName("pushButton_7")
        self.label_11 = QtWidgets.QLabel(self.frame_32)
        self.label_11.setGeometry(QtCore.QRect(0, 70, 111, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_6.addWidget(self.frame_32)
        self.frame_33 = QtWidgets.QFrame(self.frame_5)
        self.frame_33.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_33.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_33.setObjectName("frame_33")
        self.pushButton_8 = QtWidgets.QPushButton(self.frame_33)
        self.pushButton_8.setGeometry(QtCore.QRect(0, 0, 111, 61))
        self.pushButton_8.setStyleSheet("border-radius: 5px;\n"
"border: 1px solid white;\n"
"margin-right: 2px;")
        self.pushButton_8.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("source/icons/Analog.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_8.setIcon(icon8)
        self.pushButton_8.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_8.setObjectName("pushButton_8")
        self.label_12 = QtWidgets.QLabel(self.frame_33)
        self.label_12.setGeometry(QtCore.QRect(0, 70, 111, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_6.addWidget(self.frame_33)
        self.frame_34 = QtWidgets.QFrame(self.frame_5)
        self.frame_34.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_34.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_34.setObjectName("frame_34")
        self.pushButton_9 = QtWidgets.QPushButton(self.frame_34)
        self.pushButton_9.setGeometry(QtCore.QRect(0, 0, 111, 61))
        self.pushButton_9.setStyleSheet("border-radius: 5px;\n"
"border: 1px solid white;\n"
"margin-right: 2px;")
        self.pushButton_9.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("source/icons/digital-wave.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_9.setIcon(icon9)
        self.pushButton_9.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_9.setObjectName("pushButton_9")
        self.label_13 = QtWidgets.QLabel(self.frame_34)
        self.label_13.setGeometry(QtCore.QRect(0, 70, 111, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_6.addWidget(self.frame_34)
        self.frame_41 = QtWidgets.QFrame(self.frame_5)
        self.frame_41.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_41.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_41.setObjectName("frame_41")
        self.pushButton_10 = QtWidgets.QPushButton(self.frame_41)
        self.pushButton_10.setGeometry(QtCore.QRect(0, 0, 111, 61))
        self.pushButton_10.setStyleSheet("border-radius: 5px;\n"
"border: 1px solid rgb(0, 85, 255);\n"
"margin-right: 2px;")
        self.pushButton_10.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("source/icons/export.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_10.setIcon(icon10)
        self.pushButton_10.setIconSize(QtCore.QSize(60, 60))
        self.pushButton_10.setObjectName("pushButton_10")
        self.label_14 = QtWidgets.QLabel(self.frame_41)
        self.label_14.setGeometry(QtCore.QRect(0, 70, 111, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_6.addWidget(self.frame_41)
        self.verticalLayout.addWidget(self.frame_5)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.add_animated_plot()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ADE9000 Management System"))
        self.label_23.setText(_translate("MainWindow", "ADE9000"))
        self.label_32.setText(_translate("MainWindow", "Voltage"))
        self.label_27.setText(_translate("MainWindow", "B"))
        self.label_31.setText(_translate("MainWindow", "200.35"))
        self.label_33.setText(_translate("MainWindow", "202.10"))
        self.label_34.setText(_translate("MainWindow", "201.90"))
        self.label_15.setText(_translate("MainWindow", "A"))
        self.label_18.setText(_translate("MainWindow", "B"))
        self.label_28.setText(_translate("MainWindow", "C"))
        self.label_124.setText(_translate("MainWindow", "Current"))
        self.label_125.setText(_translate("MainWindow", "B"))
        self.label_126.setText(_translate("MainWindow", "200.35"))
        self.label_127.setText(_translate("MainWindow", "202.10"))
        self.label_128.setText(_translate("MainWindow", "201.90"))
        self.label_129.setText(_translate("MainWindow", "A"))
        self.label_130.setText(_translate("MainWindow", "B"))
        self.label_131.setText(_translate("MainWindow", "C"))
        self.label_164.setText(_translate("MainWindow", "<html><head/><body><p>Power</p><p><br/></p></body></html>"))
        self.label_165.setText(_translate("MainWindow", "B"))
        self.label_166.setText(_translate("MainWindow", "200.35"))
        self.label_167.setText(_translate("MainWindow", "202.10"))
        self.label_168.setText(_translate("MainWindow", "201.90"))
        self.label_169.setText(_translate("MainWindow", "A"))
        self.label_170.setText(_translate("MainWindow", "B"))
        self.label_171.setText(_translate("MainWindow", "C"))
        self.label_24.setText(_translate("MainWindow", "DB Connection: OK"))
        self.label_25.setText(_translate("MainWindow", "Date: 26/04/2024 20:00 "))
        self.label_26.setText(_translate("MainWindow", "Temprature: 35 *C"))
        self.label_35.setText(_translate("MainWindow", "Status"))
        self.label_19.setText(_translate("MainWindow", "Average voltage"))
        self.label_20.setText(_translate("MainWindow", "Average current"))
        self.label_21.setText(_translate("MainWindow", "Average power"))
        self.label_22.setText(_translate("MainWindow", "Frequency"))
        self.label_30.setText(_translate("MainWindow", "58"))
        self.label.setText(_translate("MainWindow", "Setting"))
        self.label_2.setText(_translate("MainWindow", "Voltage"))
        self.label_3.setText(_translate("MainWindow", "Current"))
        self.label_8.setText(_translate("MainWindow", "Angle"))
        self.label_9.setText(_translate("MainWindow", "Power"))
        self.label_10.setText(_translate("MainWindow", "Harmonic"))
        self.label_11.setText(_translate("MainWindow", "View"))
        self.label_12.setText(_translate("MainWindow", "Analog Output"))
        self.label_13.setText(_translate("MainWindow", "Digital Output"))
        self.label_14.setText(_translate("MainWindow", "Export"))
    def add_animated_plot(self):
        # Create Matplotlib figure and canvas
        self.fig, self.ax = plt.subplots()
        self.canvas = FigureCanvas(self.fig)

        # Embed the canvas into the widget
        layout = QtWidgets.QVBoxLayout(self.visu)
        layout.addWidget(self.canvas)

        # Set up animation
        self.xLable = deque(maxlen=30)
        self.data1 = deque(maxlen=30)
        self.index = count()

        self.ani = FuncAnimation(self.fig, self.animate, interval=500)

    def animate(self, i):
        self.xLable.append(next(self.index))
        self.data1.append(random.randrange(0, 9) * 0.1 + 220)
        self.ax.clear()
        self.ax.plot(self.xLable, self.data1)
        self.ax.set_ylabel('Voltage')
        self.ax.set_facecolor("#00416A")
        self.fig.tight_layout()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
